service:
  output_dir: ./recordings
  interval_seconds: 20
  request_timeout_seconds: 8
  request_retries: 3
#  live_from_start: true
  write_info_json: true
  hls_use_mpegts: true
  ytdlp_extra_args: []

